services:
  web-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./angular.json
          target: /app/angular.json
        - action: rebuild
          path: ./package.json
